CREATE TABLE  "FARMACEUTICO" 
   (	"IDFARMACEUTICO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME_COMPLETO" VARCHAR2(100) NOT NULL ENABLE, 
	"CPF" NUMBER(11,0) NOT NULL ENABLE, 
	 CONSTRAINT "FARMACEUTICO_PK" PRIMARY KEY ("IDFARMACEUTICO")
  USING INDEX  ENABLE
   )
/

CREATE UNIQUE INDEX  "FARMACEUTICO_IDX" ON  "FARMACEUTICO" ("CPF")
/

CREATE TABLE  "FUNCIONARIO" 
   (	"IDFUNCIONARIO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME_COMPLETO" VARCHAR2(100) NOT NULL ENABLE, 
	"CPF" NUMBER(11,0) NOT NULL ENABLE, 
	 CONSTRAINT "FUNCIONARIO_PK" PRIMARY KEY ("IDFUNCIONARIO")
  USING INDEX  ENABLE
   )
/
 
CREATE TABLE  "HOSPITAL" 
   (	"IDHOSPITAL" NUMBER(10,0) NOT NULL ENABLE, 
	"NOME_HOSPITAL" VARCHAR2(200) NOT NULL ENABLE, 
	"ENDERECO_COMPLETO" VARCHAR2(255) NOT NULL ENABLE, 
	"CEP" NUMBER(8,0) NOT NULL ENABLE, 
	"CNPJ" NUMBER(14,0) NOT NULL ENABLE, 
	 CONSTRAINT "HOSPITAL_PK" PRIMARY KEY ("IDHOSPITAL")
  USING INDEX  ENABLE
   )
/
 
CREATE TABLE  "LISTA_PRODUTOS" 
   (	"IDPRESCRICAO" NUMBER(10,0) NOT NULL ENABLE, 
	"IDMEDICAMENTOS" NUMBER(10,0) NOT NULL ENABLE, 
	"QUANTIDADE" NUMBER(4,4) NOT NULL ENABLE, 
	 CONSTRAINT "LISTA_PRODUTOS_PK" PRIMARY KEY ("IDPRESCRICAO", "IDMEDICAMENTOS")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "LISTA_PRODUTOS" ADD CONSTRAINT "MEDICAMENTOS_RECEITA_FK" FOREIGN KEY ("IDMEDICAMENTOS")
	  REFERENCES  "MEDICAMENTOS" ("IDMEDICAMENTOS") ENABLE
/
ALTER TABLE  "LISTA_PRODUTOS" ADD CONSTRAINT "PRESCRICAO_RECEITA_FK" FOREIGN KEY ("IDPRESCRICAO")
	  REFERENCES  "PRESCRICAO" ("IDPRESCRICAO") ENABLE
/
 
CREATE TABLE  "MEDICAMENTOS" 
   (	"IDMEDICAMENTOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CLASSE" NUMBER(20,0) NOT NULL ENABLE, 
	"CLASSE" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_SUBCLASSE" NUMBER(20,0) NOT NULL ENABLE, 
	"SUBCLASSE" VARCHAR2(150) NOT NULL ENABLE, 
	"IDENTIFICACAO_COMERCIAL" VARCHAR2(150) NOT NULL ENABLE, 
	"NOME_COMERCIAL" VARCHAR2(150) NOT NULL ENABLE, 
	"NOME_GENERICO" VARCHAR2(150) NOT NULL ENABLE, 
	"NOME_ORDEM_PRODUCAO" VARCHAR2(150), 
	"UNIDADE" VARCHAR2(40) NOT NULL ENABLE, 
	"SIGLA" CHAR(2) NOT NULL ENABLE, 
	"CONTROLAR_FATOR_CALORICO" CHAR(1) NOT NULL ENABLE, 
	"CONTROLAR_OSMOLARIDADE" CHAR(1) NOT NULL ENABLE, 
	"FATOR_CALORICO" NUMBER(10,10), 
	"OSMOLARIDADE" NUMBER(10,10), 
	 CONSTRAINT "MEDICAMENTOS_PK" PRIMARY KEY ("IDMEDICAMENTOS")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MEDICAMENTOS_CALORICO_CK" CHECK (controlar_fator_calorico IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "MEDICAMENTOS_OSMOLARIDADE_CK" CHECK (controlar_osmolaridade IN ('S', 'N')) ENABLE
   )
/
 
CREATE TABLE  "MEDICO" 
   (	"IDFUNCIONARIO" NUMBER(10,0) NOT NULL ENABLE, 
	"CRM" VARCHAR2(12) NOT NULL ENABLE, 
	"STATUS" CHAR(1) NOT NULL ENABLE, 
	"ESPECIALIDADE" VARCHAR2(30), 
	 CONSTRAINT "MEDICO_PK" PRIMARY KEY ("IDFUNCIONARIO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MEDICO_STATUS_CK" CHECK (status IN ('A', 'D')) ENABLE
   )
/
ALTER TABLE  "MEDICO" ADD CONSTRAINT "FUNCIONARIOS_MEDICO_FK" FOREIGN KEY ("IDFUNCIONARIO")
	  REFERENCES  "FUNCIONARIO" ("IDFUNCIONARIO") ENABLE
/

CREATE UNIQUE INDEX  "MEDICO_IDX" ON  "MEDICO" ("CRM")
/
 
CREATE TABLE  "PACIENTE" 
   (	"IDPACIENTE" NUMBER(10,0) NOT NULL ENABLE, 
	"IDHOSPITAL" NUMBER(10,0) NOT NULL ENABLE, 
	"PRIMEIRO_NOME" VARCHAR2(30) NOT NULL ENABLE, 
	"NOME_MEIO" VARCHAR2(30) NOT NULL ENABLE, 
	"ULTIMO_NOME" VARCHAR2(30) NOT NULL ENABLE, 
	"DATA_NASCIMENTO" DATE NOT NULL ENABLE, 
	"CPF" NUMBER(11,0) NOT NULL ENABLE, 
	"TELEFONE" NUMBER(13,0) NOT NULL ENABLE, 
	"LEITO" VARCHAR2(10) NOT NULL ENABLE, 
	"SESSAO" VARCHAR2(10) NOT NULL ENABLE, 
	"NOME_PARENTE" VARCHAR2(100) NOT NULL ENABLE, 
	"TELEFONE_PARENTE" NUMBER(13,0) NOT NULL ENABLE, 
	 CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("IDPACIENTE")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "PACIENTE" ADD CONSTRAINT "HOSPITAL_PACIENTE_FK" FOREIGN KEY ("IDHOSPITAL")
	  REFERENCES  "HOSPITAL" ("IDHOSPITAL") ENABLE
/

CREATE UNIQUE INDEX  "PACIENTE_IDX" ON  "PACIENTE" ("CPF")
/

CREATE TABLE  "PERMISSAO_ALTERACAO" 
   (	"IDPERMISSAO" VARCHAR2(12) NOT NULL ENABLE, 
	"DATA_MODIFICAO" DATE NOT NULL ENABLE, 
	"IDFUNCIONARIO" NUMBER(10,0) NOT NULL ENABLE, 
     CONSTRAINT "TIPO_PERMISSAO_CK" CHECK (IDPERMISSAO IN ('MEDICO', 'SUPERVISOR', 'FARMACEUTICO')) ENABLE,
	 CONSTRAINT "PERMISSAO_ALTERACAO_PK" PRIMARY KEY ("IDPERMISSAO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "PERMISSAO_ALTERACAO" ADD CONSTRAINT "MEDICO_PERMISSAO_ALTERACAO_FK" FOREIGN KEY ("IDFUNCIONARIO")
	  REFERENCES  "MEDICO" ("IDFUNCIONARIO") ENABLE
/
ALTER TABLE  "PERMISSAO_ALTERACAO" ADD CONSTRAINT "SUPERVISOR_PERMISSAO_ALTERA965" FOREIGN KEY ("IDFUNCIONARIO")
	  REFERENCES  "SUPERVISOR" ("IDFUNCIONARIO") ENABLE
/

CREATE TABLE  "PRESCRICAO" 
   (	"IDPRESCRICAO" NUMBER(10,0) NOT NULL ENABLE, 
	"DATA" DATE NOT NULL ENABLE, 
	"TIPO_DE_ACESSO" VARCHAR2(15) NOT NULL ENABLE, 
	"VELOCIDADE_DE_INFUSO" NUMBER(10,4) NOT NULL ENABLE, 
	"VOLUME_TOTAL" NUMBER(10,4) NOT NULL ENABLE, 
	"LIBERACAO" CHAR(1) NOT NULL ENABLE, 
	"IDPACIENTE" NUMBER(10,0) NOT NULL ENABLE, 
	"IDFUNCIONARIO" NUMBER(10,0) NOT NULL ENABLE, 
	"IDFARMACEUTICO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PRESCRICAO_PK" PRIMARY KEY ("IDPRESCRICAO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PRESCRICAO_LIBERACAO_CK" CHECK (liberacao IN ('S', 'N', 's', 'n')) ENABLE
   )
/
ALTER TABLE  "PRESCRICAO" ADD CONSTRAINT "FARMACEUTICO_PRESCRICAO_FK" FOREIGN KEY ("IDFARMACEUTICO")
	  REFERENCES  "FARMACEUTICO" ("IDFARMACEUTICO") ENABLE
/
ALTER TABLE  "PRESCRICAO" ADD CONSTRAINT "MEDICO_PRESCRICAO_FK" FOREIGN KEY ("IDFUNCIONARIO")
	  REFERENCES  "MEDICO" ("IDFUNCIONARIO") ENABLE
/
ALTER TABLE  "PRESCRICAO" ADD CONSTRAINT "PACIENTE_PRESCRICAO_FK" FOREIGN KEY ("IDPACIENTE")
	  REFERENCES  "PACIENTE" ("IDPACIENTE") ENABLE
/

CREATE TABLE  "SUPERVISOR" 
   (	"IDFUNCIONARIO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "SUPERVISOR_PK" PRIMARY KEY ("IDFUNCIONARIO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "SUPERVISOR" ADD CONSTRAINT "FUNCIONARIO_FARMACEUTICO_FK" FOREIGN KEY ("IDFUNCIONARIO")
	  REFERENCES  "FUNCIONARIO" ("IDFUNCIONARIO") ENABLE
/

CREATE TABLE  "TRABALHA_EM" 
   (	"IDHOSPITAL" NUMBER(10,0) NOT NULL ENABLE, 
	"IDFUNCIONARIO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "TRABALHA_EM_PK" PRIMARY KEY ("IDHOSPITAL", "IDFUNCIONARIO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "TRABALHA_EM" ADD CONSTRAINT "FUNCIONARIO_TRABALHA_EM_FK" FOREIGN KEY ("IDFUNCIONARIO")
	  REFERENCES  "FUNCIONARIO" ("IDFUNCIONARIO") ENABLE
/
ALTER TABLE  "TRABALHA_EM" ADD CONSTRAINT "HOSPITAL_TRABALHA_EM_FK" FOREIGN KEY ("IDHOSPITAL")
	  REFERENCES  "HOSPITAL" ("IDHOSPITAL") ENABLE
/
