insert into MEDICAMENTOS(IDMEDICAMENTOS, ID_CLASSE, CLASSE, ID_SUBCLASSE, SUBCLASSE,IDENTIFICACAO_COMERCIAL, NOME_COMERCIAL, NOME_GENERICO, NOME_ORDEM_PRODUCAO, UNIDADE, SIGLA, CONTROLAR_FATOR_CALORICO, CONTROLAR_OSMOLARIDADE, FATOR_CALORICO, OSMOLARIDADE)
    values                         (283, 30,'Descartáveis/Material Auxiliar',  85, 'Bolsas','Bolsa EVA TPN 100 mL - B Braun','Bolsa EVA TPN 100 mL - B Braun','Bolsa EVA TPN 100 mL','Bolsa EVA TPN 100 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(53,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa EVA TPN 1000 mL - B Braun','Bolsa EVA TPN 1000 mL - B Braun','Bolsa EVA TPN 1000 mL','Bolsa EVA TPN 1000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(54,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa EVA TPN 2000 mL - B Braun','Bolsa EVA TPN 2000 mL - B Braun','Bolsa EVA TPN 2000 mL','Bolsa EVA TPN 2000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(51,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa EVA TPN 250 mL - B Braun','Bolsa EVA TPN 250 mL - B Braun','Bolsa EVA TPN 250 mL','Bolsa EVA TPN 250 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(55,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa EVA TPN 3000 mL - B Braun','Bolsa EVA TPN 3000 mL - B Braun','Bolsa EVA TPN 3000 mL','Bolsa EVA TPN 3000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(52,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa EVA TPN 500 mL - B Braun','Bolsa EVA TPN 500 mL - B Braun','Bolsa EVA TPN 500 mL','Bolsa EVA TPN 500 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(276, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Freka Bag 1000 mL - Fresenius','Bolsa Freka Bag 1000 mL - Fresenius','Bolsa Freka Bag 1000 mL - Fresenius','Bolsa Freka Bag 1000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(279, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Freka Bag 2000 mL - Fresenius','Bolsa Freka Bag 2000 mL - Fresenius','Bolsa Freka Bag 2000 mL - Fresenius','Bolsa Freka Bag 2000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(278, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Freka Bag 250 mL - Fresenius','Bolsa Freka Bag 250 mL - Fresenius','Bolsa Freka Bag 250 mL - Fresenius','Bolsa Freka Bag 250 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(281, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Freka Bag 3000 mL - Fresenius','Bolsa Freka Bag 3000 mL - Fresenius','Bolsa Freka Bag 3000 mL - Fresenius','Bolsa Freka Bag 3000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(277, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Freka Bag 500 mL - Fresenius','Bolsa Freka Bag 500 mL - Fresenius','Bolsa Freka Bag 500 mL - Fresenius','Bolsa Freka Bag 500 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(285, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Gravitacional Mix Bag EVA 100 mL - B Braun','Bolsa Gravitacional Mix Bag EVA 100 mL - B Braun','Bolsa Gravitacional Mix Bag EVA 100 mL - B Braun','Bolsa Gravitacional Mix Bag Eva 100 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(56,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Gravitacional Mix Bag EVA 3000 mL - B Braun','Bolsa Gravitacional Mix Bag EVA 3000 mL - B Braun','Bolsa Gravitacional Mix Bag EVA 3000 mL - B Braun','Bolsa Gravitacional Mix Bag Eva 3000 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(43,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex ATP 1000 mL - Halex Istar','Bolsa Halex ATP 1000 mL - Halex Istar','Bolsa ATP 1000 mL','Bolsa Halex ATP 1000 mL','Unidade','un','N','N',NULL, NULL) ;
    insert into MEDICAMENTOS values(44,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex ATP 2000 mL - Halex Istar','Bolsa Halex ATP 2000 mL - Halex Istar','Bolsa ATP 2000 mL','Bolsa Halex ATP 2000 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(41,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex ATP 300 mL - Halex Istar','Bolsa Halex ATP 300 mL - Halex Istar','Bolsa ATP 300 mL','Bolsa Halex ATP 300 mL','Unidade','un','N','N',NULL, NULL );
    insert into MEDICAMENTOS values(45,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex ATP 3000 mL - Halex Istar','Bolsa Halex ATP 3000 mL - Halex Istar','Bolsa ATP 3000 mL','Bolsa Halex ATP 3000 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(42,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex ATP 500 mL - Halex Istar','Bolsa Halex ATP 500 mL - Halex Istar','Bolsa ATP 500 mL','Bolsa Halex ATP 500 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(48,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex Gravitacional 1000 mL - Halex Istar','Bolsa Halex Gravitacional 1000 mL - Halex Istar','Bolsa  Gravitacional 1000 mL','Bolsa  Gravitacional 1000 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(179, 30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex Gravitacional 150 mL - Halex Istar','Bolsa Halex Gravitacional 150 mL - Halex Istar','Bolsa  Gravitacional 150 mL','Bolsa Halex Gravitacional 150 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(49,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex Gravitacional 2000 mL - Halex Istar','Bolsa Halex Gravitacional 2000 mL - Halex Istar','Bolsa  Gravitacional 2000 mL','Bolsa  Gravitacional 2000 mL','Unidade','un','N','N',NULL, NULL);   
    insert into MEDICAMENTOS values(46,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex Gravitacional 300 mL - Halex Istar','Bolsa Halex Gravitacional 300 mL - Halex Istar','Bolsa  Gravitacional 300 mL','Bolsa  Gravitacional 300 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(50,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex Gravitacional 3000 mL - Halex Istar','Bolsa Halex Gravitacional 3000 mL - Halex Istar','Bolsa  Gravitacional 3000 mL','Bolsa  Gravitacional 3000 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(47,  30, 'Descartáveis/Material Auxiliar', 85, 'Bolsas','Bolsa Halex Gravitacional 500 mL - Halex Istar','Bolsa Halex Gravitacional 500 mL - Halex Istar','Bolsa  Gravitacional 500 mL','Bolsa  Gravitacional 500 mL','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(127, 30, 'Descartáveis/Material Auxiliar', 86, 'Equipos', 'Equipo AIR 6 vias Pinnacle - B Braun', 'Equipo AIR 6 vias Pinnacle - B Braun', 'Equipo 6 vias', 'Equipo AIR 6 vias','Unidade','un','N','N',NULL, NULL  );
    insert into MEDICAMENTOS values(149, 30, 'Descartáveis/Material Auxiliar', 86, 'Equipos', 'Equipo Aminomix para Mix Bag 2 vias', 'Equipo Aminomix para mix Bag 2 vias', 'Equipo Aminomix para mix Bag 2 vias', 'Equipo Aminomix Bag 2 vias', 'Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(57,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar', 'Agulha 30 X 08', 'Agulha 30 X 08', 'Agulha 30 X 08', 'Agulha 30 X 08','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(58,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar', 'Agulha 40 X 12', 'Agulha 40 X 12', 'Agulha 40 X 12', 'Agulha 40 X 12','Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(151, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar', 'Clamp para Bag 1000, 2000, 3000, 4000 mL', 'Clamp para Bag 1000, 2000, 3000, 4000 mL', 'Clamp para Bag 1000, 2000, 3000, 4000 mL', NULL, 'Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(150, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar', 'Clamp para Bag 250, 500 mL', 'Clamp para Bag 250, 500 mL', 'Clamp para Bag 250, 500 mL', NULL,'Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(62,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar', 'Compressas de Gaze Estéril', 'Compressas de Gaze Estéril', 'Compressas de Gaze Estéril', NULL,'Unidade','un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(176, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Luva 6,0', 'Luva 6,0', 'Luva 6,0', 'Luva estéril 6,0','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(63,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Luva 6,5', 'Luva 6,5', 'Luva 6,5', 'Luva estéril 6,5','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(64,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Luva 7,0', 'Luva 7,0', 'Luva 7,0', 'Luva estéril 7,0','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(275, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Luva 7,5', 'Luva 7,5', 'Luva 7,5', 'Luva estéril 7,5','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(65,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Luva 8,0', 'Luva 8,0', 'Luva 8,0', 'Luva estéril 8,0','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(177, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Lâmina Bisturi 22', 'Lâmina Bisturi 22', 'Lâmina Bisturi 22', NULL,'Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(164, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Máscara Cirúrgica', 'Máscara Cirúrgica', 'Máscara Cirúrgica', NULL,'Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(153, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Máscara Comum', 'Máscara Comum', 'Máscara Comum', NULL,'Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(154, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Propé Descartável', 'Propé Descartável', 'Propé Descartável', NULL,'Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(172, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Seringa 1 mL com agulha', 'Seringa 1 mL', 'Seringa 1 mL', 'Seringa 1 mL','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(61,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Seringa 1 mL sem agulha', 'Seringa 1 mL', 'Seringa 1 mL', 'Seringa 1 mL','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(59,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Seringa 20 ml', 'Seringa 20 ml', 'Seringa 20 ml', 'Seringa 20 ml','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(180, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Seringa 3 ml', 'Seringa 3 ml', 'Seringa 3 ml', 'Seringa 3 ml','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(292, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Seringa 5 ml', 'Seringa 5 ml', 'Seringa 5 ml', 'Seringa 5 ml','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(60,  30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Seringa 60 ml', 'Seringa 60 ml', 'Seringa 60 ml', 'Seringa 60 ml','Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(155, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Touca', 'Touca', 'Touca', NULL,'Unidade', 'un','N','N',NULL, NULL);
    insert into MEDICAMENTOS values(134, 30, 'Descartáveis/Material Auxiliar', 87, 'Material Auxiliar','Tubo Siliconizado - 4 ML', 'Tubo Siliconizado', 'Tubo Siliconizado', 'Tubo Siliconizado','Unidade', 'un','N','N',NULL, NULL);


    insert into MEDICAMENTOS values(5,  29, 'Insumos', 78, 'Aminoácidos', 'Aminoplasmal 10% Poliaminoácidos - Frasco 1000 mL - Laboratórios B. Braun', 'Aminoplasmal 10% - Laboratórios B. Braun', 'Aminoácido 10% Adulto', 'Aminoácido 10% Adulto', 'Mililitro', 'ml','S', 'S', 0.4, 0.99);
    insert into MEDICAMENTOS values(40, 29, 'Insumos', 78, 'Aminoácidos', 'Aminosteril Hepa 8% - Frasco 500 mL - Fresenius', 'Aminosteril Hepa 8% - Fresenius', 'Aminoácido Hepatopata 8%','Aminoácido Hepatopata 8%- 500 mL', 'Mililitro', 'ml','S', 'S',0.32, 0.77);
    insert into MEDICAMENTOS values(167,29, 'Insumos', 78, 'Aminoácidos', 'Aminoven 10% Infant Poliaminoácidos - Frasco 100 mL- Fresenius' , 'Aminoven 10% Infant - Fresenius', 'Aminoácido Infantil 10%', 'Aminoácido 10% Infantil', 'Mililitro', 'ml','S', 'S',0.4, 0.875);
    insert into MEDICAMENTOS values(4,  29, 'Insumos', 78, 'Aminoácidos', 'Aminoven 10% Infant Poliaminoácidos - Frasco 1000 mL- Fresenius', 'Aminoven 10% Infant - Fresenius', 'Aminoácido Infantil 10%','Aminoácido 10% Infantil','Mililitro', 'ml','S', 'S',0.4, 0.875);
    insert into MEDICAMENTOS values(171,29, 'Insumos', 78, 'Aminoácidos', 'Aminoven 10% Infant Poliaminoácidos - Frasco 250 mL- Fresenius' , 'Aminoven 10% Infant - Fresenius','Aminoácido Infantil 10%','Aminoácido 10% Infantil','Mililitro', 'ml','S', 'S',0.4, 0.885);
    insert into MEDICAMENTOS values(3,  29, 'Insumos', 78, 'Aminoácidos', 'Aminoven 10% Poliaminoácidos - Frasco 1000 mL - Fresenius','Aminoven 10% Adulto - Fresenius','Aminoácido 10% Adulto','Aminoácido 10% Adulto','Mililitro', 'ml','S', 'S',0.4, 0.99);
    insert into MEDICAMENTOS values(163,29, 'Insumos', 78, 'Aminoácidos', 'Aminoven 15% Poliaminoácidos - Frasco 1000 mL - Fresenius','Aminoven 15% Adulto - Fresenius','Aminoácido 15% Adulto','Aminoácido 15% Adulto','Mililitro', 'ml','S', 'S',0.6, 1.505);
    insert into MEDICAMENTOS values(293,29, 'Insumos', 78, 'Aminoácidos', 'Amixal 10% Poliaminoácidos - Frasco 1000 mL - Laboratórios B. Braun','Amixal 10% - Frasco 1000 mL','Aminoácido Adulto 10%','Aminoácido Adulto 10%','Mililitro', 'ml','S', 'S',0.4, 0.99);
    insert into MEDICAMENTOS values(17, 29, 'Insumos', 78, 'Aminoácidos', 'Diamin 20 %- L-Alanil-L-Glutamina 200 mg/ mL -Frasco 100 mL- UCB Biopharma', 'Diamin 20%- UCB Biopharma','L-Alanil-','L-Alanil-L-Glutamina 200 mg/ mL -100 mL','Mililitro', 'ml','S', 'S',0.8, 0.921);
    insert into MEDICAMENTOS values(38, 29, 'Insumos', 78, 'Aminoácidos', 'Diamin 20 %- L-Alanil-L-Glutamina 200 mg/ mL -Frasco 50 mL- UCB Biopharma', 'L-Alanil-L-Glutamina 200 mg/ mL','L-Alanil-','L-Alanil-L-Glutamina 200 mg/ mL -50 mL','Mililitro', 'ml','S', 'S',0.8, 0.921);
    insert into MEDICAMENTOS values(16, 29, 'Insumos', 78, 'Aminoácidos', 'Dipeptiven 20%- Alanilglutamina 200 mg/ mL- Frasco de 100 mL- Fresenius', 'Dipeptiven 20%- Fresenius','Alanilglutamina','Alanilglutamina 200 mg/ mL-100 mL','Mililitro', 'ml','S', 'S',0.8, 0.921);
    insert into MEDICAMENTOS values(28, 29, 'Insumos', 78, 'Aminoácidos', 'Dipeptiven 20%- Alanilglutamina 200 mg/ mL- Frasco de 50 mL- Fresenius', 'Dipeptiven 20%- Fresenius','Alanilglutamina','Alanilglutamina 200 mg/ mL-50 mL','Mililitro', 'ml','S', 'S',0.8, 0.921);
    insert into MEDICAMENTOS values(39, 29, 'Insumos', 78, 'Aminoácidos', 'Nephrotect 10%- Poliaminoácido- Frasco 500 mL- Fresenius', 'Nephrotect 10%- Fresenius', 'Aminoácido Nefropata 10%','Aminoácido Nefropata 10%- 500 mL','Mililitro', 'ml','S', 'S',0.4, 0.96);
    insert into MEDICAMENTOS values(145, 29,'Insumos', 78, 'Aminoácidos', 'Pediamino Tau 10% Poliaminoácidos- Frasco 500 mL- B.Braun', 'PediaminoTau 10%- B.Braun', 'Aminoácido 10% Infantil','Aminoácido Infantil 10%- 500 ml','Mililitro', 'ml','S', 'S',0.4, 0.875);
    insert into MEDICAMENTOS values(6,   29,'Insumos', 78, 'Aminoácidos', 'Primene 10% Poliaminoácidos- Frasco 250 mL- Fresenius', 'Primene 10%- Fresenius', 'Aminoácido 10% Infantil','Aminoácido Infantil 10%- 250 ml','Mililitro', 'ml','S', 'S',0.4, 0.885);

 
    
